language: python
python:
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO=django==2.0.9 DRF=3.8.2 DATABASE_URL=mysql://root@localhost/test
  - DJANGO=django==2.0.9 DRF=3.8.2 DATABASE_URL=postgres://postgres@localhost/test
  - DJANGO=django==2.1.1 DRF=3.8.2 DATABASE_URL=mysql://root@localhost/test
  - DJANGO=django==2.1.1 DRF=3.8.2 DATABASE_URL=postgres://postgres@localhost/test

sudo: false
install:
  - pip install $DJANGO && pip install sphinx argparse coveralls djangorestframework==$DRF
  - if [[ "$DATABASE_URL" == postgres:* ]]; then pip install psycopg2-binary; fi
  - if [[ "$DATABASE_URL" == mysql:* ]]; then pip install mysqlclient; fi
  - python setup.py -q install
before_script:
  - psql -c 'create database test;' -U postgres
  - mysql -e 'create database test character set utf8 collate utf8_general_ci;'
script:
  coverage run --source=hvad --omit='hvad/test*' runtests.py
after_success:
  if [[ $COVERALLS_REPO_TOKEN ]]; then coveralls; fi

matrix:
  exclude:
    - python: 3.4
      env: DJANGO=django==2.1.1 DRF=3.8.2 DATABASE_URL=mysql://root@localhost/test
    - python: 3.4
      env: DJANGO=django==2.1.1 DRF=3.8.2 DATABASE_URL=postgres://postgres@localhost/test
